apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["bilbomd/backend"]'
  name: backend
  namespace: {{ .Values.namespace }}
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 3500tcp
    port: 3500
    protocol: TCP
    targetPort: 3500
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-bilbomd-backend
  sessionAffinity: None
  type: ClusterIP
